events {}
http {
    upstream app_cluster {
        server server:3000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://app_cluster;
            proxy_set_header Host $host;
        }
    }
}